services:
  api-gateway:
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
      target: builder
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npm install && npx nx daemon --start && npx nx serve api-gateway"

    ports:
      - "8080:3000"
    environment:
      - NX_DAEMON=true

  user-service:
    build:
      context: .
      dockerfile: ./apps/user-service/Dockerfile
      target: builder
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npm install && npx nx daemon && npx nx serve user-service"
    ports:
      - "3001:3001"
    environment:
      - NX_DAEMON=true