version: '3.8'

services:
  # The API Gateway Service
  api-gateway:
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
      args:
        APP_NAME: api-gateway
    container_name: api-gateway
    ports:
      # Exposes the gateway to the outside world on port 8080
      - "8080:3000"
    environment:
      # These variables are available inside the container
      - PORT=3000
      # Docker Compose automatically creates a network.
      # Services can talk to each other using their service name as the hostname.
      - USER_SERVICE_HOST=user-service # <-- IMPORTANT!
      - USER_SERVICE_PORT=3001
    depends_on:
      - user-service
    networks:
      - tiktok_clone_net

  # The User Management Service
  user-service:
    build:
      context: .
      dockerfile: ./apps/user-service/Dockerfile
      args:
        APP_NAME: user-service
    container_name: user-service
    # No ports needed here, as it's only accessed internally by the gateway
    # This is more secure. If you need to access it directly for debugging, you can add:
    # ports:
    #   - "3001:3001"
    environment:
      - PORT=3001
    networks:
      - tiktok_clone_net

networks:
  tiktok_clone_net:
    driver: bridge